# typed: strong
# frozen_string_literal: true

require "sorbet-runtime"
require "shellwords"

require "dependabot/gradle/file_parser"
require "dependabot/gradle/file_updater"

module Dependabot
  module Gradle
    class FileUpdater
      class LockfileUpdater
        extend T::Sig

        sig { params(dependency_files: T::Array[Dependabot::DependencyFile]).void }
        def initialize(dependency_files:)
          @dependency_files = dependency_files
        end

        sig { params(build_file: Dependabot::DependencyFile).returns(T::Array[Dependabot::DependencyFile]) }
        def update_lockfiles(build_file)
          root_dir = determine_root_dir(build_file: build_file)
          lockfiles = dependency_files.select do |file|
            next false unless file.name.end_with?(".lockfile")

            if root_dir == "/" || root_dir == file.directory
              true
            else
              file_path = File.join(file.directory, file.name)
              file_path.start_with?("#{root_dir}/") || file_path == root_dir
            end
          end

          return dependency_files unless lockfiles.any?

          updated_files = dependency_files.dup
          SharedHelpers.in_a_temporary_directory do |temp_dir|
            populate_temp_directory(temp_dir)

            cwd = File.join(temp_dir, root_dir == "/" ? "" : root_dir.delete_prefix("/"))

            # Proxy settings via properties (command line args don't work)
            write_properties_file(File.join(cwd, "gradle.properties"))

            # Init script drives --write-locks across all subprojects
            init_script_path = File.join(cwd, "dependabot-locking.init.gradle")
            write_init_script(init_script_path)

            command_parts = [
              "gradle",
              "--init-script", init_script_path,
              "dependabotResolveAll",
              "--write-locks",
              "--no-daemon"
            ]
            command = Shellwords.join(command_parts)

            Dir.chdir(cwd) do
              SharedHelpers.run_shell_command(command, cwd: cwd)
              update_lockfiles_content(temp_dir, lockfiles, updated_files)
            rescue SharedHelpers::HelperSubprocessFailed => e
              Dependabot.logger.error("Failed to update lockfiles: #{e.message}")
              return updated_files
            end
          end
          updated_files
        end

        sig do
          params(
            temp_dir: T.any(Pathname, String),
            lockfiles: T::Array[Dependabot::DependencyFile],
            updated_lockfiles: T::Array[Dependabot::DependencyFile]
          ).void
        end
        def update_lockfiles_content(temp_dir, lockfiles, updated_lockfiles)
          lockfiles.each do |file|
            lockfile_path = File.join(temp_dir, file.directory, file.name)
            unless File.exist?(lockfile_path)
              Dependabot.logger.warn(
                "Lockfile #{file.name} was not regenerated by Gradle. " \
                "This may indicate a configuration issue or missing resolvable dependencies."
              )
              next
            end

            f_content = File.read(lockfile_path)
            next if f_content == file.content

            tmp_file = file.dup
            tmp_file.content = f_content
            updated_lockfiles[T.must(updated_lockfiles.index(file))] = tmp_file
          end
        end

        sig { params(build_file: Dependabot::DependencyFile).returns(String) }
        def determine_root_dir(build_file:)
          settings_file = find_settings_file(build_file)
          if settings_file
            settings_dir = File.dirname(settings_file.name)
            return File.join(build_file.directory, settings_dir == "." ? "" : settings_dir)
          end

          # Version catalog lives at gradle/libs.versions.toml, one level below root
          if build_file.name.end_with?("/gradle/libs.versions.toml") || build_file.name == "gradle/libs.versions.toml"
            catalog_dir = File.dirname(build_file.name, 2)
            normalized = catalog_dir == "." ? "" : catalog_dir
            return File.join(build_file.directory, normalized)
          end

          build_file_dir = File.dirname(build_file.name)
          normalized = build_file_dir == "." ? "" : build_file_dir
          File.join(build_file.directory, normalized)
        end

        private

        sig { returns(T::Array[Dependabot::DependencyFile]) }
        attr_reader :dependency_files

        sig { params(temp_dir: T.any(Pathname, String)).void }
        def populate_temp_directory(temp_dir)
          @dependency_files.each do |file|
            in_path_name = File.join(temp_dir, file.directory, file.name)
            FileUtils.mkdir_p(File.dirname(in_path_name))
            File.write(in_path_name, file.content)
          end
        end

        sig { params(file_name: String).void }
        def write_properties_file(file_name) # rubocop:disable Metrics/PerceivedComplexity
          http_proxy = ENV.fetch("HTTP_PROXY", nil)
          https_proxy = ENV.fetch("HTTPS_PROXY", nil)
          http_split = http_proxy&.split(":")
          https_split = https_proxy&.split(":")
          http_proxy_host = http_split&.fetch(1, nil)&.gsub("//", "") || "host.docker.internal"
          https_proxy_host = https_split&.fetch(1, nil)&.gsub("//", "") || "host.docker.internal"
          http_proxy_port = http_split&.fetch(2) || "1080"
          https_proxy_port = https_split&.fetch(2) || "1080"
          properties_content = "
systemProp.http.proxyHost=#{http_proxy_host}
systemProp.http.proxyPort=#{http_proxy_port}
systemProp.https.proxyHost=#{https_proxy_host}
systemProp.https.proxyPort=#{https_proxy_port}"
          File.write(file_name, properties_content)
        end

        sig { params(file_name: String).void }
        def write_init_script(file_name)
          script_content = <<~GRADLE
            allprojects {
              tasks.register("dependabotResolveAll") {
                doLast {
                  configurations.findAll { it.canBeResolved }.each { it.resolve() }
                }
              }
            }
          GRADLE
          File.write(file_name, script_content)
        end

        sig { params(build_file: Dependabot::DependencyFile).returns(T.nilable(Dependabot::DependencyFile)) }
        def find_settings_file(build_file)
          settings_files = dependency_files.select do |f|
            basename = File.basename(f.name)
            basename == "settings.gradle" || basename == "settings.gradle.kts"
          end

          return nil if settings_files.empty?

          ancestor_settings = settings_files.select { |f| ancestor_of?(f, build_file) }

          # Closest ancestor — ensures included builds resolve to their own settings
          ancestor_settings.max_by do |f|
            dir = File.dirname(f.name)
            dir == "." ? 0 : dir.split("/").length
          end
        end

        sig { params(settings_file: Dependabot::DependencyFile, build_file: Dependabot::DependencyFile).returns(T::Boolean) }
        def ancestor_of?(settings_file, build_file)
          build_dir = File.dirname(build_file.name)
          normalized_build = build_dir == "." ? "" : build_dir
          settings_dir = File.dirname(settings_file.name)
          normalized_settings = settings_dir == "." ? "" : settings_dir

          normalized_settings.empty? ||
            normalized_build == normalized_settings ||
            normalized_build.start_with?("#{normalized_settings}/")
        end
      end
    end
  end
end
